In [34]:
import pandas as pd  #Base de datos y datos iniciales
df= pd.read_excel("Base de Operaciones Credito TEC.xlsx", sheet_name= "Operaciones")
df.head()

,folio,Empresa,RFC,Cliente,folio 1,Status,Estatus_Cobranza,Solicitud,Fecha_Deposito,Fecha_de_primer_pago,loan_name,Monto,Plazo,Tasa_con_impuesto,Tasa_sin_impuesto,Frecuencia,Cuota,Cuotas
0,PPS721703558,Spin Crédito,CLI000001XXX,CLIENTE 00001,PPS721703558,Liquidado,Liquidado,2024-12-17,2024-12-17,2024-12-20,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,200.84,6
1,PPS776127481,Spin Crédito,CLI000002XXX,CLIENTE 00002,PPS776127481,Liquidado,Liquidado,2024-12-19,2024-12-19,2024-12-24,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,201.85,6
2,SIM-ID00001-01,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-01,Liquidado,Liquidado,2025-01-17,2025-01-17,2025-02-17,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5956.11,6
3,SIM-ID00001-02,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-02,Liquidado,Liquidado,2025-02-17,2025-02-17,2025-03-17,Préstamo Personal Spinner no Late Fee,35000.0,6,86.99,74.99,Mensual,6948.79,6
4,SIM-ID00001-03,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-03,Liquidado,Liquidado,2025-03-17,2025-03-17,2025-04-17,Préstamo Personal Spinner no Late Fee,40000.0,6,86.99,74.99,Mensual,7941.48,6

In [35]:
df.shape # Cantidad de filas (1009) y cantidad de columnas (18)

(10009, 18)

In [36]:
columns_text = df.select_dtypes(include="object").columns
for col in columns_text:
    df[col]=df[col].str.strip()
    # Quitamos espacios innecesarios al inicio o final del nombre de las columnas

In [37]:
print("Filas duplicadas encontradas:", df.duplicated().sum())
df = df.drop_duplicates()

Filas duplicadas encontradas: 0

In [38]:
print(df.isnull().sum())
#Comprobamos que no haya columnas con valores nulos

folio                   0
Empresa                 0
RFC                     0
Cliente                 0
folio 1                 0
Status                  0
Estatus_Cobranza        0
Solicitud               0
Fecha_Deposito          0
Fecha_de_primer_pago    0
loan_name               0
Monto                   0
Plazo                   0
Tasa_con_impuesto       0
Tasa_sin_impuesto       0
Frecuencia              0
Cuota                   0
Cuotas                  0
dtype: int64

In [39]:
df.dropna()

,folio,Empresa,RFC,Cliente,folio 1,Status,Estatus_Cobranza,Solicitud,Fecha_Deposito,Fecha_de_primer_pago,loan_name,Monto,Plazo,Tasa_con_impuesto,Tasa_sin_impuesto,Frecuencia,Cuota,Cuotas
0,PPS721703558,Spin Crédito,CLI000001XXX,CLIENTE 00001,PPS721703558,Liquidado,Liquidado,2024-12-17,2024-12-17,2024-12-20,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,200.84,6
1,PPS776127481,Spin Crédito,CLI000002XXX,CLIENTE 00002,PPS776127481,Liquidado,Liquidado,2024-12-19,2024-12-19,2024-12-24,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,201.85,6
2,SIM-ID00001-01,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-01,Liquidado,Liquidado,2025-01-17,2025-01-17,2025-02-17,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5956.11,6
3,SIM-ID00001-02,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-02,Liquidado,Liquidado,2025-02-17,2025-02-17,2025-03-17,Préstamo Personal Spinner no Late Fee,35000.0,6,86.99,74.99,Mensual,6948.79,6
4,SIM-ID00001-03,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-03,Liquidado,Liquidado,2025-03-17,2025-03-17,2025-04-17,Préstamo Personal Spinner no Late Fee,40000.0,6,86.99,74.99,Mensual,7941.48,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10004,SIM-ID00002-01,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-01,Liquidado,Liquidado,2025-01-19,2025-01-19,2025-02-19,Préstamo Personal Spinner no Late Fee,70000.0,6,86.99,74.99,Mensual,11666.67,6
10005,SIM-ID00002-02,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-02,Liquidado,Liquidado,2025-02-19,2025-02-19,2025-03-19,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5000.00,6
10006,SIM-ID00002-03,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-03,Liquidado,Liquidado,2025-03-19,2025-03-19,2025-04-19,Préstamo Personal Spinner no Late Fee,195000.0,6,86.99,74.99,Mensual,32500.00,6
10007,SIM-ID00002-04,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-04,Liquidado,Liquidado,2025-04-19,2025-04-19,2025-05-19,Préstamo Personal Spinner no Late Fee,25000.0,6,86.99,74.99,Mensual,4166.67,6
10008,SIM-ID00002-05,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-05,Liquidado,Liquidado,2025-05-19,2025-05-19,2025-06-19,Préstamo Personal Spinner no Late Fee,60000.0,6,86.99,74.99,Mensual,10000.00,6

In [40]:
for col in ["Solicitud", "Fecha_Deposito", "Fecha_de_primer_pago"]:
    df[col] = pd.to_datetime(df[col])
    #Corroborar formato fechas

In [41]:
df["Status_cod"] = df["Status"].map({"Activo": 0, "Liquidado": 1})
df["Frecuencia_cod"] = df["Frecuencia"].map({"Semanal": 0, "Mensual": 1})
#Mapeo de variables por categoria

In [42]:
salida = "Base_Operaciones_CreditoFEMSA_LIMPIA.xlsx"
df.to_excel(salida, index=False)